function clean(v,max=5000){return String(v??'').replace(/\s+/g,' ').trim().slice(0,max)}
function decodeHtml(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function textOf(html){return decodeHtml(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')).trim()}
async function fetchText(url,timeout=6000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; SimpleReviewMaker/2.0)','accept-language':'ko-KR,ko;q=0.9'},signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
function norm(s){return String(s||'').toLowerCase().replace(/ice|hot/gi,'').replace(/[^가-힣a-z0-9]+/g,'')}
function bigrams(s){const x=norm(s),a=[];if(x.length<2)return x?[x]:[];for(let i=0;i<x.length-1;i++)a.push(x.slice(i,i+2));return [...new Set(a)]}
function dice(a,b){const A=bigrams(a),B=bigrams(b);if(!A.length||!B.length)return 0;let n=0;for(const x of A)if(B.includes(x))n++;return 2*n/(A.length+B.length)}
function menuish(s){const x=clean(s,80).replace(/^[\s·•:|\-]+|[\s·•:|\-]+$/g,'');if(x.length<2||x.length>38)return'';if(/(리뷰|영업|주소|전화|주차|메뉴정보|주문한 메뉴|원 내외|평점|점심|저녁|데이트|가족|가격|응대|키워드)/.test(x))return'';if(!/[가-힣A-Za-z]/.test(x))return'';return x}
function extractCandidates(html){const txt=textOf(html),out=[];const seen=new Set();const re=/([가-힣A-Za-z0-9_+().\-\s·]{2,38}?)\s*(\d{1,3}(?:,\d{3})+)\s*원/g;let m;while((m=re.exec(txt))&&out.length<120){let name=menuish(m[1]);if(!name)continue;name=name.replace(/(?:메뉴정보|메뉴 모두 보기|주문한 메뉴).*$/,'').trim();const key=norm(name)+'|'+m[2];if(!norm(name)||seen.has(key))continue;seen.add(key);out.push({name,price:Number(m[2].replace(/,/g,''))})}
const ordered=/주문한 메뉴\s+([^|]{2,100}?)(?:키워드|맛:|\.\.\.|1인당|$)/g;while((m=ordered.exec(txt))&&out.length<160){for(const part of m[1].split(/,|·|\//)){const name=menuish(part);if(name&&!seen.has(norm(name)+'|0')){seen.add(norm(name)+'|0');out.push({name,price:0})}}}
return out}
function ocrItems(text,current=''){const lines=String(text||'').split(/\r?\n/).map(s=>s.replace(/\s+/g,' ').trim()).filter(Boolean),out=[];for(const line of lines){if(/(합계|총액|부가|공급|매출|카드|승인|가맹|사업자|주소|전화|영수증|일자|시간)/.test(line))continue;const prices=[...line.matchAll(/\b\d{1,3}(?:[,.]\d{3})\b/g)].map(x=>Number(x[0].replace(/[,.]/g,'')));let qty=1;const qm=line.match(/\s(\d{1,2})\s+(?=\d{1,3}[,.]\d{3}\b)/);if(qm)qty=Math.max(1,Number(qm[1]));const first=line.search(/\d{1,3}(?:[,.]\d{3})/);const name=menuish(first>=0?line.slice(0,first):line);if(name)out.push({name,prices:[...new Set(prices.concat(prices.map(p=>qty>1&&p%qty===0?p/qty:0).filter(Boolean)))]})}
for(const part of String(current||'').split(',')){const name=menuish(part);if(name)out.push({name,prices:[]})}return out}
function canonicalSimple(s){let x=clean(s,60).replace(/\b(?:ICE|HOT)[_\s-]*/ig,'').trim();x=x.replace(/부카게|보카게|부카캐/g,'부카케').replace(/무동|무돔|우돔/g,'우동').replace(/사루/g,'자루').replace(/꼬카콜라/g,'코카콜라');return x}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'POST only'});const profileUrl=clean(req.body?.profileUrl,500),ocrText=String(req.body?.ocrText||'').slice(0,12000),current=clean(req.body?.currentMenu,500);if(!/^https:\/\/(?:www\.)?diningcode\.com\/profile\.php\?/i.test(profileUrl))return res.status(200).json({menus:[],source:'none'});try{const html=await fetchText(profileUrl),cands=extractCandidates(html),items=ocrItems(ocrText,current),matches=[];for(const it of items){let best=null;for(const c of cands){let sc=dice(it.name,c.name)*100;if(norm(c.name)===norm(it.name))sc+=80;else if(norm(c.name).includes(norm(it.name))||norm(it.name).includes(norm(c.name)))sc+=35;if(c.price&&it.prices.includes(c.price))sc+=45;if(!best||sc>best.score)best={...c,score:sc,ocr:it.name}}if(best&&best.score>=48)matches.push(best)}
const final=[];for(const m of matches.sort((a,b)=>b.score-a.score)){if(!final.some(x=>norm(x)===norm(m.name)))final.push(m.name)}
for(const part of current.split(',')){const x=canonicalSimple(part);if(x&&x.length>=2&&!/[0-9]{3,}/.test(x)&&!/(합계|매출|일자|시간|번호|주소|전화)/.test(x)&&!final.some(y=>norm(y)===norm(x))){if(/(우동|카스|콜라|아메리카노|라떼|커피|브레드|빵|케이크|떡볶이|순대|국밥|초밥|돈까스|파스타|피자|버거)/.test(x))final.push(x)}}
return res.status(200).json({menus:final.slice(0,8),candidates:cands.slice(0,25),source:'diningcode'})}catch(e){return res.status(200).json({menus:[],source:'error'})}}
