function clean(v,max=500){return String(v??'').replace(/\s+/g,' ').trim().slice(0,max)}
function decodeHtml(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function textOf(html){return decodeHtml(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')).trim()}
async function fetchText(url,timeout=6000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; SimpleReviewMaker/2.7)','accept-language':'ko-KR,ko;q=0.9'},signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
function norm(s){return String(s||'').toLowerCase().replace(/\b(?:ice|hot)\b/gi,'').replace(/[^가-힣a-z0-9]+/g,'')}
function bigrams(s){const x=norm(s),a=[];if(x.length<2)return x?[x]:[];for(let i=0;i<x.length-1;i++)a.push(x.slice(i,i+2));return [...new Set(a)]}
function dice(a,b){const A=bigrams(a),B=bigrams(b);if(!A.length||!B.length)return 0;let n=0;for(const x of A)if(B.includes(x))n++;return 2*n/(A.length+B.length)}
function lev(a,b){a=norm(a);b=norm(b);if(!a)return b.length;if(!b)return a.length;const p=Array.from({length:b.length+1},(_,i)=>i),c=new Array(b.length+1);for(let i=1;i<=a.length;i++){c[0]=i;for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<=b.length;j++)p[j]=c[j]}return p[b.length]}
function levSim(a,b){const A=norm(a),B=norm(b),n=Math.max(A.length,B.length);return n?1-lev(A,B)/n:0}
function menuish(s){const x=clean(s,80).replace(/^[\s·•:|\-]+|[\s·•:|\-]+$/g,'');if(x.length<2||x.length>40)return'';if(/(리뷰|영업|주소|전화|주차|메뉴정보|주문한 메뉴|원 내외|평점|점심|저녁|데이트|가족|가격|응대|키워드)/.test(x))return'';if(!/[가-힣A-Za-z]/.test(x))return'';return x}
function extractMenus(html){const txt=textOf(html),out=[],seen=new Set();const re=/([가-힣A-Za-z0-9_+().\-\s·]{2,40}?)\s*(\d{1,3}(?:,\d{3})+)\s*원/g;let m;while((m=re.exec(txt))&&out.length<120){let name=menuish(m[1]);if(!name)continue;name=name.replace(/(?:메뉴정보|메뉴 모두 보기|주문한 메뉴).*$/,'').trim();const k=norm(name);if(!k||seen.has(k))continue;seen.add(k);out.push(name)}const ordered=/주문한 메뉴\s+([^|]{2,120}?)(?:키워드|맛:|\.\.\.|1인당|$)/g;while((m=ordered.exec(txt))&&out.length<150){for(const part of m[1].split(/,|·|\//)){const name=menuish(part),k=norm(name);if(name&&k&&!seen.has(k)){seen.add(k);out.push(name)}}}return out}
function extractProfiles(html){const raw=decodeHtml(String(html||'')).replace(/\\u002f/gi,'/').replace(/\\u003f/gi,'?').replace(/\\u003d/gi,'=').replace(/\\\//g,'/');const out=[],seen=new Set();for(const re of [/(?:https?:\/\/www\.diningcode\.com\/)?profile\.php\?rid=([A-Za-z0-9_-]+)/gi,/["']rid["']\s*:\s*["']([A-Za-z0-9_-]{6,})["']/gi]){let m;while((m=re.exec(raw))&&out.length<12){const rid=m[1];if(!seen.has(rid)){seen.add(rid);out.push(`https://www.diningcode.com/profile.php?rid=${rid}`)}}}return out}
function profileMeta(html){const txt=textOf(html);const title=((String(html).match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i)||String(html).match(/<title[^>]*>([^<]+)<\/title>/i)||[])[1]||'').replace(/\s*-\s*[^-]*?(?:맛집|다이닝코드)[\s\S]*$/i,'').replace(/\s*\|\s*다이닝코드.*$/i,'').trim();const address=(txt.match(/(?:서울특별시|서울|경기도|경기|인천광역시|인천|부산광역시|부산|대구광역시|대구|대전광역시|대전|광주광역시|광주|울산광역시|울산|세종특별자치시|세종|강원특별자치도|강원도|충청북도|충북|충청남도|충남|전북특별자치도|전라북도|전북|전라남도|전남|경상북도|경북|경상남도|경남|제주특별자치도|제주)\s+[가-힣]+(?:시|군|구)?\s+[가-힣0-9·.-]+(?:로|길)\s*\d+(?:-\d+)?(?:\s+[^\n]{0,30})?/)||[])[0]||'';return{name:title,address:clean(address,140)}}
function profileScore(place,address,meta){let s=dice(place,meta.name)*100+levSim(place,meta.name)*80;if(norm(place)===norm(meta.name))s+=120;if(address&&meta.address){if(norm(meta.address).includes(norm(address))||norm(address).includes(norm(meta.address)))s+=100;else s+=dice(address,meta.address)*60}return s}
async function resolveProfile(profileUrl,place,address){if(/^https:\/\/(?:www\.)?diningcode\.com\/profile\.php\?/i.test(profileUrl))return profileUrl;if(!place)return'';try{const list=await fetchText(`https://www.diningcode.com/list.dc?query=${encodeURIComponent(place)}`,6000),urls=extractProfiles(list);let best=null;for(const u of urls.slice(0,6)){try{const h=await fetchText(u,5000),meta=profileMeta(h),score=profileScore(place,address,meta);if(!best||score>best.score)best={u,score}}catch(_){}}return best&&best.score>=55?best.u:''}catch(_){return''}}
function splitMenus(s){return String(s||'').split(/[,/\n]|\s*·\s*/).map(x=>clean(x,60)).filter(Boolean).slice(0,8)}
function bestMatch(item,cands){let best={name:'',score:0};for(const c of cands){const A=norm(item),B=norm(c);let s=Math.max(dice(A,B)*100,levSim(A,B)*100);if(A===B)s=100;else if(A&&B&&(A.includes(B)||B.includes(A)))s=Math.max(s,88);if(s>best.score)best={name:c,score:s}}return best}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'POST only'});const place=clean(req.body?.place,100),address=clean(req.body?.placeAddress,160),profileUrl=clean(req.body?.placeProfileUrl,500),menu=clean(req.body?.menu,500),items=splitMenus(menu);if(!items.length)return res.status(200).json({checked:false,warn:false,reason:'no-menu'});try{const url=await resolveProfile(profileUrl,place,address);if(!url)return res.status(200).json({checked:false,warn:false,reason:'no-profile'});const html=await fetchText(url,6000),cands=extractMenus(html);if(cands.length<3)return res.status(200).json({checked:false,warn:false,reason:'not-enough-public-menu'});const results=items.map(item=>({item,...bestMatch(item,cands)}));const unmatched=results.filter(x=>x.score<58);const warn=unmatched.length>0;return res.status(200).json({checked:true,warn,unmatched:unmatched.map(x=>x.item),matches:results,examples:cands.slice(0,8),profileUrl:url})}catch(e){return res.status(200).json({checked:false,warn:false,reason:'check-error'})}}
