function clean(v,max=300){return String(v??'').replace(/\s+/g,' ').trim().slice(0,max)}
function decode(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function norm(s){return String(s||'').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^가-힣a-z0-9]+/g,'')}
function bigrams(s){const x=norm(s),a=[];if(x.length<2)return x?[x]:[];for(let i=0;i<x.length-1;i++)a.push(x.slice(i,i+2));return [...new Set(a)]}
function dice(a,b){const A=bigrams(a),B=bigrams(b);if(!A.length||!B.length)return 0;let n=0;for(const x of A)if(B.includes(x))n++;return 2*n/(A.length+B.length)}
function variants(q){const raw=clean(q,80),set=new Set();if(raw)set.add(raw);const noBranch=raw.replace(/\s*(본점|직영점|지점|점)\s*$/,'').trim();if(noBranch&&noBranch!==raw)set.add(noBranch);return [...set].slice(0,2)}
async function getJson(url,headers){const c=new AbortController(),t=setTimeout(()=>c.abort(),2200);try{const r=await fetch(url,{headers:{accept:'application/json',...headers},signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
function score(q,p,addressHint=''){let s=dice(q,p.name)*100;const Q=norm(q),N=norm(p.name);if(Q===N)s+=160;else if(N.includes(Q))s+=90;else if(Q.includes(N))s+=55;if(addressHint){const A=norm(addressHint),B=norm(p.address);if(A&&B&&(A.includes(B)||B.includes(A)))s+=100;else s+=dice(A,B)*50}return s}
function mapItems(items,q,addressHint,mode){const out=[];for(const x of items||[]){const name=decode(x.title),address=clean(x.roadAddress||x.address,160);if(!name||!address)continue;const p={id:`naver:${norm(name)}:${norm(address)}`,name,address,phone:'',category:decode(x.category),placeUrl:x.link||'',profileUrl:'',x:String(x.mapx||''),y:String(x.mapy||''),source:'naver',sourceLabel:mode==='naver-api-hub'?'네이버 공식 지역검색':'네이버 지역검색',context:(mode==='naver-api-hub'?'네이버 공식 지역검색':'네이버 지역검색')+(x.category?' · '+decode(x.category):'')};p.score=Math.round(score(q,p,addressHint));const dup=out.find(v=>norm(v.name)===norm(p.name)&&norm(v.address)===norm(p.address));if(!dup)out.push(p)}out.sort((a,b)=>b.score-a.score);return out.slice(0,5)}
async function hubSearch(q,addressHint){const id=process.env.NAVER_API_HUB_CLIENT_ID||process.env.NCP_NAVER_CLIENT_ID||'',secret=process.env.NAVER_API_HUB_CLIENT_SECRET||process.env.NCP_NAVER_CLIENT_SECRET||'';if(!id||!secret)return null;const jobs=variants(q).map(term=>getJson(`https://naverapihub.apigw.ntruss.com/search/v1/local?query=${encodeURIComponent(term)}&display=5&start=1&sort=random&format=json`,{'X-NCP-APIGW-API-KEY-ID':id,'X-NCP-APIGW-API-KEY':secret}));const settled=await Promise.allSettled(jobs),items=[];for(const r of settled)if(r.status==='fulfilled')items.push(...(r.value.items||[]));return{available:true,mode:'naver-api-hub',places:mapItems(items,q,addressHint,'naver-api-hub')}
async function legacySearch(q,addressHint){const id=process.env.NAVER_CLIENT_ID||process.env.NAVER_SEARCH_CLIENT_ID||'',secret=process.env.NAVER_CLIENT_SECRET||process.env.NAVER_SEARCH_CLIENT_SECRET||'';if(!id||!secret)return null;const jobs=variants(q).map(term=>getJson(`https://openapi.naver.com/v1/search/local.json?query=${encodeURIComponent(term)}&display=5&start=1&sort=random`,{'X-Naver-Client-Id':id,'X-Naver-Client-Secret':secret}));const settled=await Promise.allSettled(jobs),items=[];for(const r of settled)if(r.status==='fulfilled')items.push(...(r.value.items||[]));return{available:true,mode:'naver-legacy',places:mapItems(items,q,addressHint,'naver-legacy')}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store, max-age=0');const q=clean(req.query?.q||'',80),address=clean(req.query?.address||'',120);if(q.length<2)return res.status(200).json({available:false,mode:'none',places:[]});try{const hub=await hubSearch(q,address);if(hub)return res.status(200).json(hub);const legacy=await legacySearch(q,address);if(legacy)return res.status(200).json(legacy);return res.status(200).json({available:false,mode:'no-naver-key',places:[]})}catch(_){return res.status(200).json({available:false,mode:'naver-error',places:[]})}}
