function clean(v,max=500){return String(v??'').replace(/\s+/g,' ').trim().slice(0,max)}
function decodeHtml(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function htmlToText(html){return decodeHtml(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')).trim()}
async function fetchText(url,timeout=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; SimpleReviewMaker/2.4)','accept-language':'ko-KR,ko;q=0.9,en;q=0.4'},signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
function normalize(s){return String(s||'').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^가-힣a-z0-9]+/g,'').trim()}
function jamo(s){return normalize(s).normalize('NFD')}
function lev(a,b){a=String(a||'');b=String(b||'');if(!a)return b.length;if(!b)return a.length;const prev=Array(b.length+1).fill(0).map((_,i)=>i),cur=Array(b.length+1);for(let i=1;i<=a.length;i++){cur[0]=i;for(let k=1;k<=b.length;k++)cur[k]=Math.min(cur[k-1]+1,prev[k]+1,prev[k-1]+(a[i-1]===b[k-1]?0:1));for(let k=0;k<=b.length;k++)prev[k]=cur[k]}return prev[b.length]}
function levSim(a,b){a=jamo(a);b=jamo(b);const n=Math.max(a.length,b.length);return n?1-lev(a,b)/n:0}
function bigrams(s){const x=normalize(s);if(x.length<2)return new Set(x?[x]:[]);const o=new Set();for(let i=0;i<x.length-1;i++)o.add(x.slice(i,i+2));return o}
function dice(a,b){const A=bigrams(a),B=bigrams(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return 2*n/(A.size+B.size)}
function digitSim(a,b){a=String(a||'').replace(/\D/g,'');b=String(b||'').replace(/\D/g,'');if(!a||!b)return 0;if(a===b)return 1;const aa=a.slice(-8),bb=b.slice(-8),n=Math.max(aa.length,bb.length);return n?1-lev(aa,bb)/n:0}
function addressSim(a,b){if(!a||!b)return 0;const A=normalize(a),B=normalize(b);if(!A||!B)return 0;if(A.includes(B)||B.includes(A))return .95;return Math.max(dice(A,B),levSim(A,B))}
const FOOD=['떡볶이','순대국','순댓국','국밥','해장국','감자탕','설렁탕','곰탕','갈비탕','칼국수','수제비','냉면','우동','라멘','라면','초밥','스시','돈까스','돈카츠','파스타','피자','치킨','버거','햄버거','카페','커피','베이커리','빵집','식당','분식','고기','삼겹살','곱창','막창','족발','보쌈','김밥','닭갈비','쭈꾸미','샤브샤브'].sort((a,b)=>b.length-a.length)
function stripFoodSuffix(q){let x=normalize(q),category='';for(const w of FOOD)if(x.endsWith(w)){category=w;x=x.slice(0,-w.length);break}return{root:x,category}}
function queryVariants(q,address=''){const raw=clean(q,80),compact=normalize(raw),{root,category}=stripFoodSuffix(raw),set=new Set([raw,compact]);if(root){if(category)set.add(`${root} ${category}`);set.add(root);if(root.length>=4)set.add(root.slice(0,Math.ceil(root.length*.7)))}if(compact.length>=5)set.add(compact.slice(0,Math.max(2,Math.ceil(compact.length*.55))));const region=(String(address||'').match(/(?:서울|인천|부산|대구|대전|광주|울산|세종|경기|강원|충북|충남|전북|전남|경북|경남|제주)\s+[가-힣]{1,8}(?:시|군|구)?/)||[])[0];if(region&&raw)set.add(`${raw} ${region}`);return[...set].map(x=>clean(x,80)).filter(x=>x.length>=2).slice(0,8)}
function scoreName(query,name){const q=normalize(query),n=normalize(name);if(!q||!n)return 0;let s=0;if(n===q)s+=120;if(n.includes(q))s+=65;if(q.includes(n))s+=50;s+=Math.round(dice(q,n)*55);s+=Math.round(Math.max(0,levSim(q,n))*75);const qr=stripFoodSuffix(q).root,nr=stripFoodSuffix(n).root;if(qr&&nr){if(qr===nr)s+=45;else if(nr.includes(qr)||qr.includes(nr))s+=25;s+=Math.round(levSim(qr,nr)*30)}return s}
function firstMatch(html,patterns){for(const re of patterns){const m=String(html||'').match(re);if(m&&m[1])return decodeHtml(m[1]).replace(/\\u([0-9a-f]{4})/gi,(_,x)=>String.fromCharCode(parseInt(x,16))).trim()}return''}
function urlish(html){return decodeHtml(String(html||'')).replace(/\\u002f/gi,'/').replace(/\\u003a/gi,':').replace(/\\u003f/gi,'?').replace(/\\u003d/gi,'=').replace(/\\\//g,'/').replace(/%2f/gi,'/').replace(/%3a/gi,':').replace(/%3f/gi,'?').replace(/%3d/gi,'=')}
function extractProfileUrls(html){const raw=urlish(html),urls=[],seen=new Set(),patterns=[/(?:https?:\/\/www\.diningcode\.com\/)?profile\.php\?rid=([A-Za-z0-9_-]+)/gi,/www\.diningcode\.com\/profile\.php\?rid=([A-Za-z0-9_-]+)/gi,/["']rid["']\s*:\s*["']([A-Za-z0-9_-]{6,})["']/gi];for(const re of patterns){let m;while((m=re.exec(raw))&&urls.length<45){const rid=m[1];if(!seen.has(rid)){seen.add(rid);urls.push(`https://www.diningcode.com/profile.php?rid=${rid}`)}}}return urls}
function parseProfile(html,url,query,hints){const text=htmlToText(html);let name=firstMatch(html,[/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i,/<title[^>]*>([^<]+)<\/title>/i,/<h1[^>]*>([^<]+)<\/h1>/i]);name=name.replace(/\s*-\s*[^-]*?(?:맛집|다이닝코드)[\s\S]*$/i,'').replace(/\s*\|\s*다이닝코드.*$/i,'').replace(/\s*-\s*다이닝코드.*$/i,'').trim();let address=firstMatch(html,[/"streetAddress"\s*:\s*"([^"]+)"/i,/"roadAddress"\s*:\s*"([^"]+)"/i,/"address"\s*:\s*"((?:서울|경기|인천|부산|대구|대전|광주|울산|세종|강원|충청|전라|경상|제주)[^"]+)"/i]);if(!address){const m=text.match(/(?:서울특별시|서울|경기도|경기|인천광역시|인천|부산광역시|부산|대구광역시|대구|대전광역시|대전|광주광역시|광주|울산광역시|울산|세종특별자치시|세종|강원특별자치도|강원도|충청북도|충북|충청남도|충남|전북특별자치도|전라북도|전북|전라남도|전남|경상북도|경북|경상남도|경남|제주특별자치도|제주)\s+[가-힣]+(?:시|군|구)?\s+[가-힣0-9·.-]+(?:로|길)\s*\d+(?:-\d+)?(?:\s+[^\n]{0,30})?/);if(m)address=m[0].replace(/\s+/g,' ').trim()}const phone=(text.match(/0\d{1,2}[-\s]?\d{3,4}[-\s]?\d{4}/)||[])[0]||'',keywords=text.match(/(?:혼밥|데이트|가족외식|점심식사|저녁식사|셀프바|셀프코너|주차|지역주민이찾는|캐주얼한|깔끔한|매콤한|조용한|푸짐한|가성비좋은)/g)||[],context=[...new Set(keywords)].slice(0,4).join(' · '),rid=(url.match(/[?&]rid=([^&]+)/)||[])[1]||'';let hintScore=0;const ps=digitSim(hints.phone,phone);if(ps>=.99)hintScore+=100;else if(ps>=.82)hintScore+=65;else if(ps>=.68)hintScore+=30;const as=addressSim(hints.address,address);if(as>=.9)hintScore+=80;else if(as>=.67)hintScore+=45;else if(as>=.5)hintScore+=20;const score=scoreName(query,name)+hintScore;return{id:rid,name:clean(name,80),address:clean(address,140),phone:clean(phone,30),context,profileUrl:url,score,hintScore,nameScore:scoreName(query,name)}}
async function discoverDC(q){try{return extractProfileUrls(await fetchText(`https://www.diningcode.com/list.dc?query=${encodeURIComponent(q)}`,6000))}catch(_){return[]}}
async function discoverSearch(engine,q){try{const target=`site:www.diningcode.com/profile.php ${q}`,url=engine==='naver'?`https://search.naver.com/search.naver?where=web&query=${encodeURIComponent(target)}`:`https://search.daum.net/search?w=tot&q=${encodeURIComponent(target)}`;return extractProfileUrls(await fetchText(url,5400))}catch(_){return[]}}
async function collectUrls(query,hints){const variants=queryVariants(query,hints.address),qs=[...variants];if(hints.phone&&hints.phone.length>=9)qs.push(hints.phone);if(hints.address)qs.push(hints.address);const jobs=[];for(let i=0;i<qs.length;i++){const q=qs[i];jobs.push(discoverDC(q));if(i<7)jobs.push(discoverSearch('naver',q),discoverSearch('daum',q))}const settled=await Promise.allSettled(jobs),set=new Set();for(const s of settled){if(s.status!=='fulfilled')continue;for(const u of s.value||[]){set.add(u);if(set.size>=32)break}if(set.size>=32)break}return[...set]}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');const q=clean(req.query?.q||req.body?.q,80),phone=clean(req.query?.phone||req.body?.phone,30).replace(/\D/g,''),address=clean(req.query?.address||req.body?.address,120),hints={phone,address};if((!q||q.length<2)&&!phone&&!address)return res.status(200).json({query:q,places:[]});try{const urls=await collectUrls(q,hints),settled=await Promise.allSettled(urls.map(async url=>parseProfile(await fetchText(url,5400),url,q,hints))),byId=new Map();for(const s of settled){if(s.status!=='fulfilled'||!s.value?.name)continue;const p=s.value;if(p.score<20&&p.hintScore<25)continue;const prev=byId.get(p.id);if(!prev||p.score>prev.score)byId.set(p.id,p)}const places=[...byId.values()].sort((a,b)=>b.score-a.score||b.hintScore-a.hintScore||Number(Boolean(b.address))-Number(Boolean(a.address))).slice(0,15);return res.status(200).json({query:q,places,relaxed:queryVariants(q,address).slice(1),hintsUsed:{phone:Boolean(phone),address:Boolean(address)},totalCandidates:places.length})}catch(e){return res.status(200).json({query:q,places:[],error:'매장 후보 검색에 실패했습니다.'})}}
