function clean(v,max=500){return String(v??'').replace(/\s+/g,' ').trim().slice(0,max)}
function decodeHtml(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function stripTags(s){return decodeHtml(String(s||'').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function htmlToText(html){return decodeHtml(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')).trim()}
async function fetchText(url,timeout=6500,headers={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; SimpleReviewMaker/3.0)','accept-language':'ko-KR,ko;q=0.9,en;q=0.4',...headers},signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
async function fetchJson(url,timeout=6500,headers={}){const text=await fetchText(url,timeout,{accept:'application/json',...headers});return JSON.parse(text)}
function normalize(s){return String(s||'').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^가-힣a-z0-9]+/g,'').trim()}
function jamo(s){return normalize(s).normalize('NFD')}
function lev(a,b){a=String(a||'');b=String(b||'');if(!a)return b.length;if(!b)return a.length;const prev=Array(b.length+1).fill(0).map((_,i)=>i),cur=Array(b.length+1);for(let i=1;i<=a.length;i++){cur[0]=i;for(let k=1;k<=b.length;k++)cur[k]=Math.min(cur[k-1]+1,prev[k]+1,prev[k-1]+(a[i-1]===b[k-1]?0:1));for(let k=0;k<=b.length;k++)prev[k]=cur[k]}return prev[b.length]}
function levSim(a,b){a=jamo(a);b=jamo(b);const n=Math.max(a.length,b.length);return n?Math.max(0,1-lev(a,b)/n):0}
function bigrams(s){const x=normalize(s);if(x.length<2)return new Set(x?[x]:[]);const o=new Set();for(let i=0;i<x.length-1;i++)o.add(x.slice(i,i+2));return o}
function dice(a,b){const A=bigrams(a),B=bigrams(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return 2*n/(A.size+B.size)}
function digitSim(a,b){a=String(a||'').replace(/\D/g,'');b=String(b||'').replace(/\D/g,'');if(!a||!b)return 0;if(a===b)return 1;const aa=a.slice(-8),bb=b.slice(-8),n=Math.max(aa.length,bb.length);return n?Math.max(0,1-lev(aa,bb)/n):0}
function addressSim(a,b){if(!a||!b)return 0;const A=normalize(a),B=normalize(b);if(!A||!B)return 0;if(A.includes(B)||B.includes(A))return .98;return Math.max(dice(A,B),levSim(A,B))}
const FOOD=['뚝배기떡볶이','떡볶이','순대국','순댓국','국밥','해장국','감자탕','설렁탕','곰탕','갈비탕','칼국수','수제비','냉면','우동','라멘','라면','초밥','스시','돈까스','돈카츠','파스타','피자','치킨','버거','햄버거','카페','커피','베이커리','빵집','식당','분식','고기','삼겹살','곱창','막창','족발','보쌈','김밥','닭갈비','쭈꾸미','샤브샤브'].sort((a,b)=>b.length-a.length)
const BRANCH=['본점','직영점','지점','점','전문점','전문','매장'].sort((a,b)=>b.length-a.length)
function stripSuffix(q){let x=normalize(q),category='';for(const w of FOOD)if(x.endsWith(w)){category=w;x=x.slice(0,-w.length);break}for(const w of BRANCH){if(x.endsWith(w)&&x.length>w.length+1){x=x.slice(0,-w.length);break}}return{root:x,category}}
function regionTokens(address=''){const s=clean(address,120),out=[];const m=s.match(/(서울(?:특별시)?|인천(?:광역시)?|부산(?:광역시)?|대구(?:광역시)?|대전(?:광역시)?|광주(?:광역시)?|울산(?:광역시)?|세종(?:특별자치시)?|경기(?:도)?|강원(?:특별자치도|도)?|충북|충남|전북|전남|경북|경남|제주(?:특별자치도)?)\s+([가-힣]{1,8}(?:시|군|구)?)(?:\s+([가-힣0-9·.-]+(?:동|읍|면|리)))?/);if(m){out.push(`${m[1]} ${m[2]}`);if(m[3])out.push(m[3])}return out}
function formatPhone(p){const d=String(p||'').replace(/\D/g,'');if(d.length===11)return `${d.slice(0,3)}-${d.slice(3,7)}-${d.slice(7)}`;if(d.length===10&&d.startsWith('02'))return `${d.slice(0,2)}-${d.slice(2,6)}-${d.slice(6)}`;if(d.length===10)return `${d.slice(0,3)}-${d.slice(3,6)}-${d.slice(6)}`;return d}
function queryVariants(q,address='',phone=''){const raw=clean(q,80),compact=normalize(raw),{root,category}=stripSuffix(raw),set=new Set();if(raw)set.add(raw);if(compact)set.add(compact);if(root){if(category)set.add(`${root} ${category}`);set.add(root);if(root.length>=5)set.add(root.slice(0,Math.ceil(root.length*.72)));if(root.length>=4)set.add(root.slice(0,3))}if(compact.length>=7)set.add(compact.slice(0,Math.ceil(compact.length*.58)));for(const r of regionTokens(address)){if(raw)set.add(`${raw} ${r}`);if(root)set.add(`${root} ${r}`)}if(phone){set.add(formatPhone(phone));set.add(String(phone).replace(/\D/g,''))}if(address)set.add(clean(address,80));return[...set].map(x=>clean(x,80)).filter(x=>x.length>=2).slice(0,12)}
function scoreName(query,name){const q=normalize(query),n=normalize(name);if(!q||!n)return 0;let s=0;if(n===q)s+=145;if(n.includes(q))s+=78;if(q.includes(n))s+=58;s+=Math.round(dice(q,n)*60);s+=Math.round(levSim(q,n)*85);const qr=stripSuffix(q).root,nr=stripSuffix(n).root;if(qr&&nr){if(qr===nr)s+=60;else if(nr.includes(qr)||qr.includes(nr))s+=38;s+=Math.round(levSim(qr,nr)*35)}return s}
function hintScore(hints,p){let s=0;const ps=digitSim(hints.phone,p.phone);if(ps>=.99)s+=130;else if(ps>=.82)s+=80;else if(ps>=.68)s+=35;const as=addressSim(hints.address,p.address);if(as>=.93)s+=105;else if(as>=.74)s+=65;else if(as>=.55)s+=30;return s}
function providerBoost(source){return source==='kakao'?38:source==='naver'?32:source==='diningcode'?8:0}
function candidateScore(query,hints,p){return scoreName(query,p.name)+hintScore(hints,p)+providerBoost(p.source)}
function samePlace(a,b){const ps=digitSim(a.phone,b.phone),as=addressSim(a.address,b.address),ns=Math.max(dice(a.name,b.name),levSim(a.name,b.name));if(ps>=.98)return true;if(as>=.9&&ns>=.42)return true;if(normalize(a.name)===normalize(b.name)&&as>=.55)return true;return false}
function mergeCandidate(a,b){const rank={kakao:3,naver:2,diningcode:1};const primary=(rank[b.source]||0)>(rank[a.source]||0)?b:a,secondary=primary===a?b:a;const sources=[...new Set([...(a.sources||[a.source]),...(b.sources||[b.source])].filter(Boolean))];return{...secondary,...primary,name:primary.name||secondary.name,address:primary.address||secondary.address,phone:primary.phone||secondary.phone,category:primary.category||secondary.category,placeUrl:primary.placeUrl||secondary.placeUrl,profileUrl:a.profileUrl||b.profileUrl||'',id:primary.id||secondary.id,sources,source:primary.source,sourceLabel:sources.map(x=>x==='kakao'?'카카오맵':x==='naver'?'네이버':x==='diningcode'?'다이닝코드':x).join(' + ')}}
function addMerged(list,p,query,hints){if(!p?.name)return;const x={...p,name:clean(p.name,90),address:clean(p.address,150),phone:clean(p.phone,30),category:clean(p.category,100),context:clean(p.context,140),sources:p.sources||[p.source]};x.score=candidateScore(query,hints,x);x.hintScore=hintScore(hints,x);const i=list.findIndex(v=>samePlace(v,x));if(i>=0){const m=mergeCandidate(list[i],x);m.score=Math.max(list[i].score,x.score)+8;m.hintScore=Math.max(list[i].hintScore||0,x.hintScore||0);list[i]=m}else list.push(x)}
async function kakaoSearch(queries,query,hints){const key=process.env.KAKAO_REST_API_KEY||process.env.KAKAO_MAP_REST_API_KEY||'';if(!key)return[];const out=[];for(const q of queries.slice(0,7)){for(const page of [1,2]){try{const u=`https://dapi.kakao.com/v2/local/search/keyword.json?query=${encodeURIComponent(q)}&size=15&page=${page}`;const d=await fetchJson(u,6000,{Authorization:`KakaoAK ${key}`});for(const x of d.documents||[]){addMerged(out,{source:'kakao',id:`kakao:${x.id}`,name:x.place_name,address:x.road_address_name||x.address_name,phone:x.phone,category:x.category_name,placeUrl:x.place_url,profileUrl:'',x:x.x,y:x.y,context:`카카오맵 · ${x.category_group_name||x.category_name||'장소'}`},query,hints)}if(d.meta?.is_end)break}catch(_){break}}if(out.length>=35)break}return out}
async function naverSearch(queries,query,hints){const id=process.env.NAVER_CLIENT_ID||process.env.NAVER_SEARCH_CLIENT_ID||'',secret=process.env.NAVER_CLIENT_SECRET||process.env.NAVER_SEARCH_CLIENT_SECRET||'';if(!id||!secret)return[];const out=[];for(const q of queries.slice(0,7)){try{const u=`https://openapi.naver.com/v1/search/local.json?query=${encodeURIComponent(q)}&display=5&start=1`;const d=await fetchJson(u,6000,{'X-Naver-Client-Id':id,'X-Naver-Client-Secret':secret});for(const x of d.items||[]){addMerged(out,{source:'naver',id:`naver:${normalize(stripTags(x.title))}:${normalize(x.roadAddress||x.address)}`,name:stripTags(x.title),address:x.roadAddress||x.address,phone:x.telephone||'',category:stripTags(x.category),placeUrl:x.link||'',profileUrl:'',x:x.mapx||'',y:x.mapy||'',context:`네이버 · ${stripTags(x.category)||'장소'}`},query,hints)}}catch(_){ }if(out.length>=20)break}return out}
function firstMatch(html,patterns){for(const re of patterns){const m=String(html||'').match(re);if(m&&m[1])return decodeHtml(m[1]).replace(/\\u([0-9a-f]{4})/gi,(_,x)=>String.fromCharCode(parseInt(x,16))).trim()}return''}
function urlish(html){return decodeHtml(String(html||'')).replace(/\\u002f/gi,'/').replace(/\\u003a/gi,':').replace(/\\u003f/gi,'?').replace(/\\u003d/gi,'=').replace(/\\\//g,'/').replace(/%2f/gi,'/').replace(/%3a/gi,':').replace(/%3f/gi,'?').replace(/%3d/gi,'=')}
function extractProfileUrls(html){const raw=urlish(html),urls=[],seen=new Set(),patterns=[/(?:https?:\/\/www\.diningcode\.com\/)?profile\.php\?rid=([A-Za-z0-9_-]+)/gi,/www\.diningcode\.com\/profile\.php\?rid=([A-Za-z0-9_-]+)/gi,/["']rid["']\s*:\s*["']([A-Za-z0-9_-]{6,})["']/gi];for(const re of patterns){let m;while((m=re.exec(raw))&&urls.length<50){const rid=m[1];if(!seen.has(rid)){seen.add(rid);urls.push(`https://www.diningcode.com/profile.php?rid=${rid}`)}}}return urls}
function parseProfile(html,url,query,hints){const text=htmlToText(html);let name=firstMatch(html,[/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i,/<title[^>]*>([^<]+)<\/title>/i,/<h1[^>]*>([^<]+)<\/h1>/i]);name=name.replace(/\s*-\s*[^-]*?(?:맛집|다이닝코드)[\s\S]*$/i,'').replace(/\s*\|\s*다이닝코드.*$/i,'').replace(/\s*-\s*다이닝코드.*$/i,'').trim();let address=firstMatch(html,[/"streetAddress"\s*:\s*"([^"]+)"/i,/"roadAddress"\s*:\s*"([^"]+)"/i,/"address"\s*:\s*"((?:서울|경기|인천|부산|대구|대전|광주|울산|세종|강원|충청|전라|경상|제주)[^"]+)"/i]);if(!address){const m=text.match(/(?:서울특별시|서울|경기도|경기|인천광역시|인천|부산광역시|부산|대구광역시|대구|대전광역시|대전|광주광역시|광주|울산광역시|울산|세종특별자치시|세종|강원특별자치도|강원도|충청북도|충북|충청남도|충남|전북특별자치도|전라북도|전북|전라남도|전남|경상북도|경북|경상남도|경남|제주특별자치도|제주)\s+[가-힣]+(?:시|군|구)?\s+[가-힣0-9·.-]+(?:로|길)\s*\d+(?:-\d+)?(?:\s+[^\n]{0,30})?/);if(m)address=m[0].replace(/\s+/g,' ').trim()}const phone=(text.match(/0\d{1,2}[-\s]?\d{3,4}[-\s]?\d{4}/)||[])[0]||'',keywords=text.match(/(?:혼밥|데이트|가족외식|점심식사|저녁식사|셀프바|셀프코너|주차|지역주민이찾는|캐주얼한|깔끔한|매콤한|조용한|푸짐한|가성비좋은)/g)||[],rid=(url.match(/[?&]rid=([^&]+)/)||[])[1]||'';return{source:'diningcode',id:`dc:${rid}`,name:clean(name,80),address:clean(address,140),phone:clean(phone,30),category:'',context:`다이닝코드${keywords.length?' · '+[...new Set(keywords)].slice(0,3).join(' · '):''}`,profileUrl:url,placeUrl:url}}
async function discoverDC(q){try{return extractProfileUrls(await fetchText(`https://www.diningcode.com/list.dc?query=${encodeURIComponent(q)}`,6000))}catch(_){return[]}}
async function discoverSearch(engine,q){try{const target=`site:www.diningcode.com/profile.php ${q}`,url=engine==='naver'?`https://search.naver.com/search.naver?where=web&query=${encodeURIComponent(target)}`:`https://search.daum.net/search?w=tot&q=${encodeURIComponent(target)}`;return extractProfileUrls(await fetchText(url,5400))}catch(_){return[]}}
async function diningCodeSearch(queries,query,hints){const jobs=[];for(let i=0;i<queries.length;i++){const q=queries[i];jobs.push(discoverDC(q));if(i<7)jobs.push(discoverSearch('naver',q),discoverSearch('daum',q))}const settled=await Promise.allSettled(jobs),urls=new Set();for(const s of settled){if(s.status!=='fulfilled')continue;for(const u of s.value||[]){urls.add(u);if(urls.size>=38)break}if(urls.size>=38)break}const profiles=await Promise.allSettled([...urls].map(async u=>parseProfile(await fetchText(u,5400),u,query,hints))),out=[];for(const p of profiles)if(p.status==='fulfilled'&&p.value?.name)addMerged(out,p.value,query,hints);return out}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');const q=clean(req.query?.q||req.body?.q,80),phone=clean(req.query?.phone||req.body?.phone,30).replace(/\D/g,''),address=clean(req.query?.address||req.body?.address,120),hints={phone,address};if((!q||q.length<2)&&!phone&&!address)return res.status(200).json({query:q,places:[],providers:{kakao:false,naver:false,diningcode:true}});const variants=queryVariants(q,address,phone);try{const [ka,na,dc]=await Promise.all([kakaoSearch(variants,q,hints),naverSearch(variants,q,hints),diningCodeSearch(variants,q,hints)]),all=[];for(const p of [...ka,...na,...dc])addMerged(all,p,q,hints);for(const p of all){p.score=candidateScore(q,hints,p);p.hintScore=hintScore(hints,p);const labels=(p.sources||[p.source]).map(x=>x==='kakao'?'카카오맵':x==='naver'?'네이버':x==='diningcode'?'다이닝코드':x);p.sourceLabel=[...new Set(labels)].join(' + ');p.context=[p.sourceLabel,p.category,p.phone].filter(Boolean).join(' · ')}all.sort((a,b)=>b.score-a.score||b.hintScore-a.hintScore||Number(Boolean(b.address))-Number(Boolean(a.address)));const places=all.filter(p=>p.score>=18||p.hintScore>=25).slice(0,20);return res.status(200).json({query:q,places,relaxed:variants.slice(1),hintsUsed:{phone:Boolean(phone),address:Boolean(address)},providers:{kakao:Boolean(process.env.KAKAO_REST_API_KEY||process.env.KAKAO_MAP_REST_API_KEY),naver:Boolean((process.env.NAVER_CLIENT_ID||process.env.NAVER_SEARCH_CLIENT_ID)&&(process.env.NAVER_CLIENT_SECRET||process.env.NAVER_SEARCH_CLIENT_SECRET)),diningcode:true},totalCandidates:places.length})}catch(e){return res.status(200).json({query:q,places:[],providers:{kakao:false,naver:false,diningcode:true},error:'매장 후보 검색에 실패했습니다.'})}}
