function clean(v,max=500){return String(v??'').replace(/\s+/g,' ').trim().slice(0,max)}
function decodeHtml(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function stripTags(s){return decodeHtml(String(s||'').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function htmlToText(html){return decodeHtml(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')).trim()}
async function fetchText(url,timeout=3200,headers={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; SimpleReviewMaker/4.0)','accept-language':'ko-KR,ko;q=0.9,en;q=0.4',...headers},signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
async function fetchJson(url,timeout=3200,headers={}){return JSON.parse(await fetchText(url,timeout,{accept:'application/json',...headers}))}
function normalize(s){return String(s||'').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^가-힣a-z0-9]+/g,'')}
function lev(a,b){a=normalize(a);b=normalize(b);if(!a)return b.length;if(!b)return a.length;const p=Array.from({length:b.length+1},(_,i)=>i),c=new Array(b.length+1);for(let i=1;i<=a.length;i++){c[0]=i;for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<=b.length;j++)p[j]=c[j]}return p[b.length]}
function levSim(a,b){const A=normalize(a),B=normalize(b),n=Math.max(A.length,B.length);return n?Math.max(0,1-lev(A,B)/n):0}
function bigrams(s){const x=normalize(s),o=new Set();if(x.length<2){if(x)o.add(x);return o}for(let i=0;i<x.length-1;i++)o.add(x.slice(i,i+2));return o}
function dice(a,b){const A=bigrams(a),B=bigrams(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return 2*n/(A.size+B.size)}
function digitSim(a,b){a=String(a||'').replace(/\D/g,'');b=String(b||'').replace(/\D/g,'');if(!a||!b)return 0;if(a===b)return 1;const A=a.slice(-8),B=b.slice(-8),n=Math.max(A.length,B.length);return n?Math.max(0,1-lev(A,B)/n):0}
function addressSim(a,b){if(!a||!b)return 0;const A=normalize(a),B=normalize(b);if(!A||!B)return 0;if(A.includes(B)||B.includes(A))return .98;return Math.max(dice(A,B),levSim(A,B))}
function scoreName(q,n){const Q=normalize(q),N=normalize(n);if(!Q||!N)return 0;let s=Math.max(dice(Q,N)*80,levSim(Q,N)*90);if(Q===N)s+=160;else if(N.includes(Q))s+=90;else if(Q.includes(N))s+=55;return s}
function hintScore(h,p){let s=0,ps=digitSim(h.phone,p.phone),as=addressSim(h.address,p.address);if(ps>=.98)s+=150;else if(ps>=.8)s+=80;if(as>=.9)s+=130;else if(as>=.7)s+=70;return s}
function queryVariants(q,address='',phone=''){const raw=clean(q,80),set=new Set(),compact=normalize(raw);if(raw)set.add(raw);if(compact&&compact!==raw)set.add(compact);const noBranch=raw.replace(/\s*(본점|직영점|지점|점)\s*$/,'').trim();if(noBranch&&noBranch!==raw)set.add(noBranch);if(address)set.add(clean(address,80));if(phone){const d=String(phone).replace(/\D/g,'');if(d)set.add(d)}return[...set].filter(x=>x.length>=2).slice(0,4)}
function sourceLabel(s){return s==='kakao'?'카카오맵':s==='naver'?'네이버':s==='kakao-public'?'카카오맵 공개정보':s==='naver-public'?'네이버 공개정보':s==='diningcode'?'다이닝코드':'장소정보'}
function finalize(list,q,hints,source){const out=[];for(const p of list){if(!p?.name||!p?.address)continue;const x={...p,name:clean(p.name,90),address:clean(p.address,160),phone:clean(p.phone,30),category:clean(p.category,100),source};x.score=scoreName(q,x.name)+hintScore(hints,x);x.hintScore=hintScore(hints,x);x.sourceLabel=sourceLabel(source);x.context=[x.sourceLabel,x.category,x.phone].filter(Boolean).join(' · ');const dup=out.find(v=>(x.phone&&digitSim(v.phone,x.phone)>.98)||(normalize(v.name)===normalize(x.name)&&addressSim(v.address,x.address)>.86));if(!dup)out.push(x)}out.sort((a,b)=>b.score-a.score||b.hintScore-a.hintScore);return out}
async function kakaoSearch(queries,q,hints){const key=process.env.KAKAO_REST_API_KEY||process.env.KAKAO_MAP_REST_API_KEY||'';if(!key)return[];const raw=[];for(const term of queries.slice(0,3)){try{const d=await fetchJson(`https://dapi.kakao.com/v2/local/search/keyword.json?query=${encodeURIComponent(term)}&size=15&page=1`,2800,{Authorization:`KakaoAK ${key}`});for(const x of d.documents||[])raw.push({id:`kakao:${x.id}`,name:x.place_name,address:x.road_address_name||x.address_name,phone:x.phone,category:x.category_name,placeUrl:x.place_url,profileUrl:'',x:x.x,y:x.y})}catch(_){}}return finalize(raw,q,hints,'kakao')}
async function naverSearch(queries,q,hints){const id=process.env.NAVER_CLIENT_ID||process.env.NAVER_SEARCH_CLIENT_ID||'',secret=process.env.NAVER_CLIENT_SECRET||process.env.NAVER_SEARCH_CLIENT_SECRET||'';if(!id||!secret)return[];const raw=[];for(const term of queries.slice(0,3)){try{const d=await fetchJson(`https://openapi.naver.com/v1/search/local.json?query=${encodeURIComponent(term)}&display=5&start=1`,2800,{'X-Naver-Client-Id':id,'X-Naver-Client-Secret':secret});for(const x of d.items||[])raw.push({id:`naver:${normalize(stripTags(x.title))}:${normalize(x.roadAddress||x.address)}`,name:stripTags(x.title),address:x.roadAddress||x.address,phone:x.telephone||'',category:stripTags(x.category),placeUrl:x.link||'',profileUrl:''})}catch(_){}}return finalize(raw,q,hints,'naver')}
function urlish(html){return decodeHtml(String(html||'')).replace(/\\u002f/gi,'/').replace(/\\u003a/gi,':').replace(/\\u003f/gi,'?').replace(/\\u003d/gi,'=').replace(/\\\//g,'/').replace(/%2f/gi,'/').replace(/%3a/gi,':').replace(/%3f/gi,'?').replace(/%3d/gi,'=')}
function extractMapUrls(html){const raw=urlish(html),out=[],seen=new Set(),pats=[['kakao-public',/https?:\/\/place\.map\.kakao\.com\/(\d+)/gi,m=>`https://place.map.kakao.com/${m[1]}`],['naver-public',/https?:\/\/(?:m\.)?place\.naver\.com\/(?:restaurant|place)\/(\d+)(?:\/home)?/gi,m=>`https://m.place.naver.com/restaurant/${m[1]}/home`]];for(const [source,re,make] of pats){let m;while((m=re.exec(raw))&&out.length<12){const url=make(m),k=source+url;if(!seen.has(k)){seen.add(k);out.push({source,url})}}}return out}
function firstMatch(html,patterns){for(const re of patterns){const m=String(html||'').match(re);if(m?.[1])return decodeHtml(m[1]).replace(/\\u([0-9a-f]{4})/gi,(_,x)=>String.fromCharCode(parseInt(x,16))).trim()}return''}
function parseMapPage(html,url,source){const text=htmlToText(html);let name=firstMatch(html,[/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i,/<title[^>]*>([^<]+)<\/title>/i,/"name"\s*:\s*"([^"]{2,80})"/i]);name=stripTags(name).replace(/\s*[-|]\s*(?:네이버|카카오맵|카카오|NAVER).*$/i,'').replace(/\s*:\s*네이버.*$/i,'').trim();let address=firstMatch(html,[/"roadAddress"\s*:\s*"([^"]+)"/i,/"road_address"\s*:\s*"([^"]+)"/i,/"address_name"\s*:\s*"([^"]+)"/i]);if(!address){const m=text.match(/(?:서울특별시|서울|경기도|경기|인천광역시|인천|부산광역시|부산|대구광역시|대구|대전광역시|대전|광주광역시|광주|울산광역시|울산|세종특별자치시|세종|강원특별자치도|강원도|충청북도|충북|충청남도|충남|전북특별자치도|전라북도|전북|전라남도|전남|경상북도|경북|경상남도|경남|제주특별자치도|제주)\s+[가-힣]+(?:시|군|구)?\s+[^\n]{0,65}?(?:로|길)\s*\d+(?:-\d+)?(?:\s+[^\n]{0,20})?/);if(m)address=clean(m[0],160)}const phone=(text.match(/0\d{1,2}[-\s]?\d{3,4}[-\s]?\d{4}/)||[])[0]||'';return{name,address,phone,category:'',placeUrl:url,profileUrl:'',id:`${source}:${normalize(name)}:${normalize(address)}`}}
async function publicMapSearch(queries,q,hints){const terms=queries.slice(0,2),discover=await Promise.allSettled(terms.flatMap(term=>[fetchText(`https://search.naver.com/search.naver?where=nexearch&query=${encodeURIComponent(term)}`,2600).then(extractMapUrls),fetchText(`https://search.daum.net/search?w=tot&q=${encodeURIComponent(term)}`,2600).then(extractMapUrls)]));const urls=[],seen=new Set();for(const r of discover)if(r.status==='fulfilled')for(const x of r.value){const k=x.source+x.url;if(!seen.has(k)){seen.add(k);urls.push(x)}if(urls.length>=8)break}const pages=await Promise.allSettled(urls.slice(0,8).map(async x=>({source:x.source,p:parseMapPage(await fetchText(x.url,2800),x.url,x.source)})));const bySource={'kakao-public':[],'naver-public':[]};for(const r of pages)if(r.status==='fulfilled'&&r.value.p.name&&r.value.p.address)bySource[r.value.source].push(r.value.p);const ka=finalize(bySource['kakao-public'],q,hints,'kakao-public'),na=finalize(bySource['naver-public'],q,hints,'naver-public');return ka.length?ka:na}
function extractProfileUrls(html){const raw=urlish(html),out=[],seen=new Set();for(const re of [/(?:https?:\/\/www\.diningcode\.com\/)?profile\.php\?rid=([A-Za-z0-9_-]+)/gi,/["']rid["']\s*:\s*["']([A-Za-z0-9_-]{6,})["']/gi]){let m;while((m=re.exec(raw))&&out.length<12){const rid=m[1];if(!seen.has(rid)){seen.add(rid);out.push(`https://www.diningcode.com/profile.php?rid=${rid}`)}}}return out}
function parseProfile(html,url){const text=htmlToText(html);let name=firstMatch(html,[/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i,/<title[^>]*>([^<]+)<\/title>/i]);name=name.replace(/\s*-\s*[^-]*?(?:맛집|다이닝코드)[\s\S]*$/i,'').replace(/\s*\|\s*다이닝코드.*$/i,'').trim();let address=firstMatch(html,[/"streetAddress"\s*:\s*"([^"]+)"/i,/"roadAddress"\s*:\s*"([^"]+)"/i]);if(!address){const m=text.match(/(?:서울특별시|서울|경기도|경기|인천광역시|인천|부산광역시|부산|대구광역시|대구|대전광역시|대전|광주광역시|광주|울산광역시|울산|세종특별자치시|세종|강원특별자치도|강원도|충청북도|충북|충청남도|충남|전북특별자치도|전라북도|전북|전라남도|전남|경상북도|경북|경상남도|경남|제주특별자치도|제주)\s+[가-힣]+(?:시|군|구)?\s+[가-힣0-9·.-]+(?:로|길)\s*\d+(?:-\d+)?(?:\s+[^\n]{0,25})?/);if(m)address=clean(m[0],150)}const phone=(text.match(/0\d{1,2}[-\s]?\d{3,4}[-\s]?\d{4}/)||[])[0]||'',rid=(url.match(/[?&]rid=([^&]+)/)||[])[1]||'';return{id:`dc:${rid}`,name,address,phone,category:'',profileUrl:url,placeUrl:url}}
async function diningCodeSearch(queries,q,hints){const urls=new Set();for(const term of queries.slice(0,2)){try{for(const u of extractProfileUrls(await fetchText(`https://www.diningcode.com/list.dc?query=${encodeURIComponent(term)}`,3000)))urls.add(u)}catch(_){}}const pages=await Promise.allSettled([...urls].slice(0,8).map(async u=>parseProfile(await fetchText(u,2800),u)));return finalize(pages.filter(r=>r.status==='fulfilled').map(r=>r.value),q,hints,'diningcode')}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');const q=clean(req.query?.q||req.body?.q,80),phone=clean(req.query?.phone||req.body?.phone,30).replace(/\D/g,''),address=clean(req.query?.address||req.body?.address,120),hints={phone,address};if((!q||q.length<2)&&!phone&&!address)return res.status(200).json({query:q,places:[],mode:'none'});const variants=queryVariants(q,address,phone);const hasKakao=Boolean(process.env.KAKAO_REST_API_KEY||process.env.KAKAO_MAP_REST_API_KEY),hasNaver=Boolean((process.env.NAVER_CLIENT_ID||process.env.NAVER_SEARCH_CLIENT_ID)&&(process.env.NAVER_CLIENT_SECRET||process.env.NAVER_SEARCH_CLIENT_SECRET));try{if(hasKakao){const ka=await kakaoSearch(variants,q,hints);if(ka.length)return res.status(200).json({query:q,places:ka.slice(0,12),mode:'kakao-api',providers:{kakao:true,naver:hasNaver,diningcode:true}})}if(hasNaver){const na=await naverSearch(variants,q,hints);if(na.length)return res.status(200).json({query:q,places:na.slice(0,10),mode:'naver-api',providers:{kakao:hasKakao,naver:true,diningcode:true}})}const pm=await publicMapSearch(variants,q,hints);if(pm.length)return res.status(200).json({query:q,places:pm.slice(0,10),mode:pm[0].source==='kakao-public'?'kakao-public':'naver-public',providers:{kakao:hasKakao,naver:hasNaver,diningcode:true}});const dc=await diningCodeSearch(variants,q,hints);return res.status(200).json({query:q,places:dc.slice(0,10),mode:'diningcode',providers:{kakao:hasKakao,naver:hasNaver,diningcode:true}})}catch(e){return res.status(200).json({query:q,places:[],mode:'error',error:'매장 후보 검색에 실패했습니다.'})}}
